[CICD] Add Buildkite test pipeline to workflows (#5)
Add Buildkite test pipeline to workflows

## Purpose
Transfer the testing process defined in `.buildkite/test-pipeline.yaml`
to GitHub Actions and implement the corresponding workflow configuration
in the `workflows/*. yaml` file.

## Test Plan
Run a new GitHub Actions workflow locally for validation

## Test Result

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist
</summary>

- [x] Most of the existing test cases pass, with a pass rate above 85%;
- [x] CI run time remains stable;
- [x] Log outputs are clear and traceable.

---------

Co-authored-by: zihugithub <fbye@baai.ac.cn>
Co-authored-by: liyuzhuo <lee.yuzhuo@gmail.com>

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -2,8 +2,10 @@ name: pre-commit
 
 on:
   pull_request:
+    branches: [ "main" ]
+    types: [opened, synchronize, reopened]
   push:
-    branches: [main]
+    branches: main
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -15,14 +17,57 @@ permissions:
 jobs:
   pre-commit:
     runs-on: ubuntu-latest
+    env:
+      PRID: ${{ github.event.pull_request.number }}
+      BRANCH: main
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
-      with:
-        python-version: "3.12"
-    - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
-    - run: echo "::add-matcher::.github/workflows/matchers/markdownlint.json"
-    - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
-    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
-      with:
-        extra_args: --all-files --hook-stage manual
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.base.ref }}
+
+      - name: Merge PR to sub-branch
+        run: |
+          git fetch origin pull/${PRID}/merge
+          git checkout -b test FETCH_HEAD
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.10"
+
+      - name: Install dependencies
+        run: |
+          pip install pre-commit==4.2.0
+
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
+        with:
+          python-version: "3.12"
+      - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
+      - run: echo "::add-matcher::.github/workflows/matchers/markdownlint.json"
+      - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
+
+      - name: Run pre-commit
+        run: |
+          set +e
+          if ! [[ $(pre-commit --version) == *"4.2.0"* ]]; then
+              pip install pre-commit==4.2.0
+          fi
+
+          diff_files=$(git diff --name-only --diff-filter=ACMR ${BRANCH})
+          num_diff_files=$(echo "$diff_files" | wc -l)
+          echo -e "Different files between pr and ${BRANCH}:\n${diff_files}\n"
+
+          echo "Checking codestyle by pre-commit ..."
+          pre-commit run --files ${diff_files};check_error=$?
+
+          echo "*****************************************************************"
+          if [ ${check_error} != 0 ];then
+              echo "Your PR codestyle check failed."
+          else
+              echo "Your PR codestyle check passed."
+          fi
+          echo "*****************************************************************"
+
+          exit ${check_error}
